[package]
name = "uart-hammer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
clap = { version = "4.5.47", features = ["derive"] }
serialport = { version = "4.7.3", default-features = false }
thiserror = "2.0.16"
